apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    stringData:
      admin-password: "${POSTGRESQL_ADMIN_PASSWORD}"
      database-password: "${POSTGRESQL_PASSWORD}"
      database-user: "${POSTGRESQL_USER}"
      connection-string: "User ID=${POSTGRESQL_USER};Password=${POSTGRESQL_PASSWORD};Host=${NAME}${SUFFIX};Port=5432;Database=${POSTGRESQL_DATABASE_NAME}"
    type: Opaque
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the PostgreSQL instance.
    required: true
    value: postgresql
  - description: A name suffix used for all objects
    displayName: Suffix
    name: SUFFIX
    required: false
    value: "-dev"
  - name: POSTGRESQL_USER
    displayName: PostgreSQL Connection Username
    description: Username for PostgreSQL user that will be used for accessing the database.
    required: true
    value: sbuser
  - name: POSTGRESQL_PASSWORD
    displayName: PostgreSQL Connection Password
    description: Password for the PostgreSQL connection user.
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: POSTGRESQL_ADMIN_PASSWORD
    displayName: PostgreSQL Admin Password
    description: Password for the 'postgres' PostgreSQL administrative account.
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: POSTGRESQL_DATABASE_NAME
    displayName: PostgreSQL Database Name
    description: The name of the PostgreSQL database.
    required: true
    value: schoolbus
