#!/bin/bash
#
# The 'run' script performs simple tests that verifies usability
# of the image
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
#
# DEBUG environment variable, if not empty, makes 'run' to log every step
# of testing.
#
# Example usage: $ sudo ./test/run

IMAGE_NAME=${IMAGE_NAME:-dotnet/dotnet-20-runtime-rhel7}

if [ "$DEBUG" != "" ]; then
  set -x
fi

info() {
  echo -e "\n\e[1m[INFO] $@\e[0m\n"
}

test_cmd() {
  local run_cmd="$1"
  local expected="$2"

  info "Running command '${run_cmd}'"
  out=$(docker run --rm ${IMAGE_NAME} "${run_cmd}" 2>&1)
  if ! echo "${out}" | grep -q "${expected}"; then
    echo "ERROR[/bin/bash -c "${run_cmd}"] Expected '${expected}', got '${out}'"
    exit 1
  fi
}

info "Testing ${IMAGE_NAME}"

# Since we built the candidate image locally, we don't want S2I attempt to pull
# it from Docker hub
s2i_args="--force-pull=false"

test_cmd "dotnet --info" "Microsoft .NET Core Shared Framework Host"
test_cmd "dotnet" "Usage: dotnet"

info "All tests finished successfully."
