// API Requests
export const REQUESTS_BEGIN = 'REQUESTS_BEGIN';
export const REQUESTS_END = 'REQUESTS_END';
export const REQUESTS_ERROR = 'REQUESTS_ERROR';
export const REQUESTS_CLEAR = 'REQUESTS_CLEAR';

// Current User
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';

// Lookups
export const UPDATE_CITIES_LOOKUP = 'UPDATE_CITIES_LOOKUP';
export const UPDATE_DISTRICTS_LOOKUP = 'UPDATE_DISTRICTS_LOOKUP';
export const UPDATE_REGIONS_LOOKUP = 'UPDATE_REGIONS_LOOKUP';
export const UPDATE_SCHOOL_DISTRICTS_LOOKUP = 'UPDATE_SCHOOL_DISTRICTS_LOOKUP';
export const UPDATE_SERVICE_AREAS_LOOKUP = 'UPDATE_SERVICE_AREAS_LOOKUP';
export const UPDATE_OWNERS_LOOKUP = 'UPDATE_OWNERS_LOOKUP';
export const UPDATE_INSPECTORS_LOOKUP = 'UPDATE_INSPECTORS_LOOKUP';
export const UPDATE_ROLES_LOOKUP = 'UPDATE_ROLES_LOOKUP';
export const UPDATE_PERMISSIONS_LOOKUP = 'UPDATE_PERMISSIONS_LOOKUP';

// UI
export const UPDATE_BUSES_UI = 'UPDATE_BUSES_UI';
export const UPDATE_OWNERS_UI = 'UPDATE_OWNERS_UI';
export const UPDATE_USERS_UI = 'UPDATE_USERS_UI';
export const UPDATE_INSPECTIONS_UI = 'UPDATE_INSPECTIONS_UI';
export const UPDATE_CONTACTS_UI = 'UPDATE_CONTACTS_UI';
export const UPDATE_USER_ROLES_UI = 'UPDATE_USER_ROLES_UI';
export const UPDATE_ROLES_UI = 'UPDATE_ROLES_UI';
export const UPDATE_HISTORY_UI = 'UPDATE_HISTORY_UI';
export const UPDATE_CCWNOTIFICATION_UI = 'UPDATE_CCWNOTIFICATION_UI';

// Search
export const UPDATE_BUSES_SEARCH = 'UPDATE_BUSES_SEARCH';
export const UPDATE_CCW_SEARCH = 'UPDATE_CCW_SEARCH';
export const UPDATE_OWNERS_SEARCH = 'UPDATE_OWNERS_SEARCH';
export const UPDATE_USERS_SEARCH = 'UPDATE_USERS_SEARCH';
export const UPDATE_ROLES_SEARCH = 'UPDATE_ROLES_SEARCH';
export const UPDATE_CCWNOTIFICATIONS_SEARCH = 'UPDATE_CCWNOTIFICATIONS_SEARCH';

// Version
export const UPDATE_VERSION = 'UPDATE_VERSION';

// Favourites
export const UPDATE_FAVOURITES = 'UPDATE_FAVOURITES';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const UPDATE_FAVOURITE = 'UPDATE_FAVOURITE';
export const DELETE_FAVOURITE = 'DELETE_FAVOURITE';

// Users
export const UPDATE_USERS = 'UPDATE_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';

// Roles/Permissions
export const UPDATE_ROLES = 'UPDATE_ROLES';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const ADD_ROLE = 'ADD_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
export const UPDATE_ROLE_PERMISSIONS = 'UPDATE_ROLE_PERMISSIONS';

// Inspectors
export const UPDATE_INSPECTORS = 'UPDATE_INSPECTORS';

// School Buses
export const UPDATE_BUSES = 'UPDATE_BUSES';
export const ADD_BUS = 'ADD_BUS';
export const UPDATE_BUS = 'UPDATE_BUS';
export const DELETE_BUS = 'DELETE_BUS';
export const UPDATE_BUS_ATTACHMENTS = 'UPDATE_BUS_ATTACHMENTS';
export const ADD_BUS_CCW = 'ADD_BUS_CCW';
export const UPDATE_BUS_CCW = 'UPDATE_BUS_CCW';
export const UPDATE_BUS_INSPECTIONS = 'UPDATE_BUS_INSPECTIONS';
export const UPDATE_BUS_NOTES = 'UPDATE_BUS_NOTES';

// Inspections
export const ADD_INSPECTION = 'ADD_INSPECTION';
export const UPDATE_INSPECTION = 'UPDATE_INSPECTION';
export const DELETE_INSPECTION = 'DELETE_INSPECTION';
export const UPDATE_INSPECTION_COUNTS = 'UPDATE_INSPECTION_COUNTS';

// Owners
export const UPDATE_OWNERS = 'UPDATE_OWNERS';
export const UPDATE_OWNER = 'UPDATE_OWNER';
export const ADD_OWNER = 'ADD_OWNER';
export const DELETE_OWNER = 'DELETE_OWNER';
export const UPDATE_OWNER_CONTACTS = 'UPDATE_OWNER_CONTACTS';
export const UPDATE_OWNER_NOTES = 'UPDATE_OWNER_NOTES';

// History
export const UPDATE_HISTORY = 'UPDATE_HISTORY';

//Contacts
export const ADD_CONTACT = 'ADD_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELECT_CONTACT';

//CCW Notifications
export const UPDATE_CCWNOTIFICATIONS = 'UPDATE_CCWNOTIFICATIONS';
export const DELETE_CCWNOTIFICATIONS = 'DELETE_CCWNOTIFICATIONS';

// Notes
export const DELETE_NOTE = 'DELETE_NOTE';
