// API Requests
export const REQUESTS_BEGIN = 'REQUESTS_BEGIN';
export const REQUESTS_END = 'REQUESTS_END';
export const REQUESTS_ERROR = 'REQUESTS_ERROR';

// Current User
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';

// Lookups
export const UPDATE_CITIES_LOOKUP = 'UPDATE_CITIES_LOOKUP';
export const UPDATE_DISTRICTS_LOOKUP = 'UPDATE_DISTRICTS_LOOKUP';
export const UPDATE_REGIONS_LOOKUP = 'UPDATE_REGIONS_LOOKUP';
export const UPDATE_SCHOOL_DISTRICTS_LOOKUP = 'UPDATE_SCHOOL_DISTRICTS_LOOKUP';
export const UPDATE_SERVICE_AREAS_LOOKUP = 'UPDATE_SERVICE_AREAS_LOOKUP';
export const UPDATE_GROUPS_LOOKUP = 'UPDATE_GROUPS_LOOKUP';
export const UPDATE_OWNERS_LOOKUP = 'UPDATE_OWNERS_LOOKUP';
export const UPDATE_INSPECTORS_LOOKUP = 'UPDATE_INSPECTORS_LOOKUP';

// UI
export const UPDATE_BUSES_UI = 'UPDATE_BUSES_UI';
export const UPDATE_OWNERS_UI = 'UPDATE_OWNERS_UI';
export const UPDATE_USERS_UI = 'UPDATE_USERS_UI';
export const UPDATE_INSPECTIONS_UI = 'UPDATE_INSPECTIONS_UI';
export const UPDATE_CONTACTS_UI = 'UPDATE_CONTACTS_UI';

// Search
export const UPDATE_BUSES_SEARCH = 'UPDATE_BUSES_SEARCH';
export const UPDATE_OWNERS_SEARCH = 'UPDATE_OWNERS_SEARCH';
export const UPDATE_USERS_SEARCH = 'UPDATE_USERS_SEARCH';

// Version
export const UPDATE_VERSION = 'UPDATE_VERSION';

// Favourites
export const UPDATE_FAVOURITES = 'UPDATE_FAVOURITES';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const UPDATE_FAVOURITE = 'UPDATE_FAVOURITE';
export const DELETE_FAVOURITE = 'DELETE_FAVOURITE';

// Users
export const UPDATE_USERS = 'UPDATE_USERS';
export const UPDATE_USER = 'UPDATE_USER';

// Inspectors
export const UPDATE_INSPECTORS = 'UPDATE_INSPECTORS';

// School buses
export const UPDATE_BUSES = 'UPDATE_BUSES';
export const UPDATE_BUS = 'UPDATE_BUS';
export const UPDATE_BUS_ATTACHMENTS = 'UPDATE_BUS_ATTACHMENTS';
export const UPDATE_BUS_CCW = 'UPDATE_BUS_CCW';
export const UPDATE_BUS_HISTORIES = 'UPDATE_BUS_HISTORIES';
export const UPDATE_BUS_INSPECTIONS = 'UPDATE_BUS_INSPECTIONS';
export const UPDATE_BUS_NOTES = 'UPDATE_BUS_NOTES';

// Inspections
export const ADD_INSPECTION = 'ADD_INSPECTION';
export const UPDATE_INSPECTION = 'UPDATE_INSPECTION';
export const DELETE_INSPECTION = 'DELETE_INSPECTION';

// Owners
export const UPDATE_OWNERS = 'UPDATE_OWNERS';
export const UPDATE_OWNER = 'UPDATE_OWNER';
