#!/bin/sh
set +x
type -t nvm && nvm deactivate
export NVM_DIR="$(git rev-parse --show-toplevel)/.nvm"
if [ ! -f "$NVM_DIR/nvm.sh" ]; then
  mkdir -p "${NVM_DIR}"
  curl -sSL -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash &>/dev/null
fi
source "$NVM_DIR/nvm.sh" &>/dev/null
METHOD=script nvm install --no-progress &>/dev/null
nvm use &>/dev/null
exec npm "$@"
